version: '3'
services:
  jupyter:
    image: yihui8776/myml:v1.0
    container_name: myml
    ports:
      - "8888:8888"
      - "6006:6006"
    environment:
      - PASSWORD=ai1234
    volumes:
      - "./notebooks:/notebooks"
    command:
      - "/run_jupyter.sh"
      - "--allow-root"

